version: '3.8'

services:
  frontend:
    build:
      context: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build:
      context: ./proxy-server
    ports:
      - "3001:3001"
    volumes:
      - ./proxy-server:/app
      - /app/node_modules
