version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    expose:
      - "80"
    depends_on:
      - backend
    networks:
      - rtm-network

  backend:
    build:
      context: ./proxy-server
    container_name: backend
    ports:
      - "3001:3001"
    restart: always
    networks:
      - rtm-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - rtm-network

networks:
  rtm-network:
    driver: bridge
